theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Data and Code Guidance by Data Editors
description: Guidance for authors wishing to create data and code supplements, and for replicators.
logo: assets/ssde-logo.jpeg
show_downloads: false
keep_files: [template-README.html]
