theme: jekyll-theme-minimal
title: AEA Data and Code Guidance
description: Guidance for authors wishing to create data and code supplements, and for replicators.
logo: assets/presentation-1559937_640.png
show_downloads: false
