project:
  type: website

website:
  title: "{{< var ssde.web_name >}}"
  favicon: ssde-logo.png
  
  repo-url: https://github.com/social-science-data-editors/new-guidance
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer: 
    center: 
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: FAQ.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/social-science-data-editors/new-guidance

  navbar:
      background: light
      logo: ssde.png
      logo-alt: "Social Science Data Editors"
      title: false
      collapse-below: lg
      left:
        - text: "Guidance"
          href: index.qmd
        - text: "Disclaimer"
          href: disclaimer.qmd
        - text: "FAQ"
          href: FAQ.qmd

      tools:
        - icon: github
          href: https://github.com/social-science-data-editors/new-guidance
          text: SSDE GitHub 

  sidebar:
  - id: guidance
    title: "Unofficial guidance by Social Science Data Editors"
    style: "floating"
    collapse-level: 1
    contents:
    # defaults to index.qmd page. This will be the page that opens up when you click the icon
      - index.qmd
      - section: "Guidance"
        contents:
          - Data_citation_guide.qmd
          - addtl-data-citation-guidance.qmd
          - Verification_guidance.md
          # - docker-guidelines.qmd
          # - guidance-reproducible-gis-analysis.qmd
          - journal-policies.qmd
          # - synthetic-fake-data-guidance.qmd
      - section: "Requested Information"
        contents:
          - Requested_information.qmd
          # - Requested_information_code.qmd
          # - Requested_information_data.qmd
          # - Requested_information_dcas.qmd
          # - Requested_information_hosting.qmd
      - section: "Samples"
        contents:
          # - sample-depositing-data-for-greater-good.qmd
          # - sample-information-data.qmd
          # - sample-report.qmd
      - section: "Templates"
        contents:
          # - template-README.qmd
          # - template_inquiry_about_DOI_by_editor.qmd
      - section: "Other"
        contents:
          # - DCAS_Commercial_data.qmd
          # - DCAS_Restricted_data.qmd
          # - Disclaimer.qmd
          - FAQ.qmd
          # - data-editors-guild-charter.qmd

  - id: disclaimer

              

format:
  html:
    theme: 
      light: cosmo
      dark: darkly

    css: styles.css
    toc: true
    linkcolor: black