project:
  type: website

website:
  title: "{{< var ssde.web_name >}}"
  favicon: ssde-logo.png 

  # temporary
  announcement: 
    icon: cone-striped
    dismissable: true
    content: "We are in the process of restructuring this website. Please bear with us, and report any issues."
    type: warning
    position: above-navbar
  
  repo-url: https://github.com/social-science-data-editors/new-guidance
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer: 
    left: "This project is maintained by [{{< var linkers.gitlink.text >}}]({{< var linkers.gitlink.url >}})"
    center: 
      - href: about.qmd
        icon: info-circle
        text: "<i class='bi bi-info-circle' role='img'></i> About"
      - href: Other/FAQ.qmd
        icon: question-circle
        text: "<i class='bi bi-question-circle' role='img'></i> FAQ"
      - href: LICENSE.qmd
        icon: license
        text: "<i class='bi bi-cc-circle' role='img'></i> License"
      - href: https://social-science-data-editors.github.io/
        icon: home
        text: "<i class='bi bi-house-fill' role='img'></i> Homepage"
    right:
      - icon: github
        href: https://github.com/social-science-data-editors/new-guidance

  navbar:
      background: light
      logo: ssde.png
      logo-alt: "Social Science Data Editors"
      title: false
      collapse-below: lg
      left:
        - text: "Guidance"
          href: index.qmd
        - text: "Disclaimer"
          href: Disclaimer.qmd
        - text: "FAQ"
          href: Other/FAQ.qmd
      right:
        - text: "Other pages"
          menu: 
            - text: Homepage
              href: https://social-science-data-editors.github.io/
            - text: "DCAS"
              href: https://datacodestandard.org/
            - text: "Template README"
              href: https://social-science-data-editors.github.io/template_README/

      # tools:
      #   - icon: github
      #     href: https://github.com/social-science-data-editors/new-guidance
      #     text: SSDE GitHub 

  sidebar:
    - id: main-sidebar
      title: "navigate"
      style: "floating"
      collapse-level: 1
      contents:
      # default opens to index.qmd page.
        - section: index.qmd
          contents:
            - Guidance/Data_citation_guide.qmd
            - Guidance/addtl-data-citation-guidance.qmd
            - Guidance/Verification_guidance.qmd
            - Guidance/docker-guidelines.qmd
            - Guidance/guidance-reproducible-gis-analysis.qmd
            - Guidance/journal-policies.qmd
            - Guidance/synthetic-fake-data-guidance.qmd
        - section: "Requested Information"
          contents:
            - Requested-Information/Requested_information.qmd
            - Requested-Information/Requested_information_code.qmd
            - Requested-Information/Requested_information_data.qmd
            - Requested-Information/Requested_information_dcas.qmd
            - Requested-Information/Requested_information_hosting.qmd
        - section: "Samples"
          contents:
            - Samples/sample-depositing-data-for-greater-good.qmd
            - Samples/sample-information-data.qmd
            - Samples/sample-report.qmd
        - section: "Templates"
          contents:
            - Templates/template-README.qmd
            - Templates/template_inquiry_about_DOI_by_editor.qmd
        - section: "Other"
          contents:
            - Other/DCAS_Commercial_data.qmd
            - Other/DCAS_Restricted_data.qmd
            - Other/data-editors-guild-charter.qmd

format:
  html:
    theme: 
      light: mytheme.scss
      # dark: darkly
    code-copy: true
    code-overflow: wrap

    css: styles.css
    toc: true
    toc-indent: 4em
    toc-depth: 4