project:
  type: website

website:
  title: "{{< var ssde.web_name >}}"
  favicon: ssde-logo.png 

  # temporary
  announcement: 
    icon: cone-striped
    dismissable: true
    content: "We are in the process of restructuring this website. Please bear with us, and report any issues."
    type: warning
    position: above-navbar
  
  repo-url: https://github.com/social-science-data-editors/new-guidance
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer: 
    left: "This project is maintained by [{{< var linkers.gitlink.text >}}]({{< var linkers.gitlink.url >}})"
    center: 
      - href: about
        icon: info-circle
        text: "<i class='bi bi-info-circle' role='img'></i> About"
      - href: Other/FAQ
        icon: question-circle
        text: "<i class='bi bi-question-circle' role='img'></i> FAQ"
      - href: LICENSE
        icon: license
        text: "<i class='bi bi-cc-circle' role='img'></i> License"
      - href: https://social-science-data-editors.github.io/
        icon: home
        text: "<i class='bi bi-house-fill' role='img'></i> Homepage"
    right:
      - icon: github
        href: https://github.com/social-science-data-editors/new-guidance

  navbar:
      background: dark
      logo: ssde.png
      logo-alt: "Social Science Data Editors"
      title: false
      collapse-below: lg
      left:
        - text: "Guidance"
          href: index
        - text: "Disclaimer"
          href: Disclaimer
        - text: "FAQ"
          href: Other/FAQ
      right:
        - text: "Other pages"
          menu: 
            - text: Homepage
              href: https://social-science-data-editors.github.io/
            - text: "DCAS"
              href: https://datacodestandard.org/
            - text: "Template README"
              href: https://social-science-data-editors.github.io/template_README/

      # tools:
      #   - icon: github
      #     href: https://github.com/social-science-data-editors/new-guidance
      #     text: SSDE GitHub 

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
    # default opens to index page.
      - index
      - journal-policies            
      - section: Guidance/Requested_information
        contents:
          - Guidance/Requested_information_code
          - Guidance/Requested_information_data
          - Guidance/Data_citation_guide
          - Guidance/addtl-data-citation-guidance
          - Guidance/guidance-reproducible-gis-analysis
          - Guidance/docker-guidelines
          - Guidance/Licensing_guidance
          - Guidance/Requested_information_dcas
          - Guidance/Requested_information_hosting
      - section: Verification/Verification_guidance
      - section: "Samples"
        contents:
          - Samples/sample-depositing-data-for-greater-good
          - Samples/sample-information-data
          - Samples/sample-report
      - section: "Templates"
        contents:
          - Templates/template-README
          - Templates/template_inquiry_about_DOI_by_editor
      - section: "Other"
        contents:
          - Other/DCAS_Commercial_data
          - Other/DCAS_Restricted_data
          - Other/data-editors-guild-charter

format:
  html:
    theme: 
      light: mytheme.scss
      # dark: darkly
    code-copy: true
    code-overflow: wrap

    css: styles.css
    toc: true
    toc-indent: 4em
    toc-depth: 4